### ISSUE TITLE
Unable to ruby get_access_token.rb

### ISSUE THREAD

**Issue by rickychew77** [mtempel/spreadsheetDemo#2]
Hi! I am new to Ruby

I get errors like this

/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- google/api_client (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from get_access_token.rb:2:in `<main>'

when I execute ruby get_access_token.rb

Not quite sure is the ruby version issues or google-api-client issues. 

Any help on this is greatly appreciated. Thanks.

**Comment by rickychew77** [comment]
UPDATE

After some reference from other online source: 

1. https://www.botreetechnologies.com/blog/google-api-authorization-with-ruby-using-long-lasting-refresh-token

This is to generate refresh token without running get_access_token.rb

2.https://github.com/googleapis/google-api-ruby-client/blob/master/MIGRATING.md#migrating-from-version-08x-to-09-or-above

Some command I modified in jobs/spread.rb to use google/apis/drive

I am able to run dashing start

However there are no value of the spreadsheet displayed. I am not sure what is wrong.
